POST http://localhost:8000/api/
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoicGFnaXkwMDMiLCJpYXQiOjE2OTE2NzUxMTEsImV4cCI6MTY5MTY3NTQxMSwiYXVkIjoiYWRtaW4iLCJpc3MiOiJwYXN5ZW50ZSIsInN1YiI6InVuZGVmaW5lZCJ9.DErNhUQGQaU-M_9NWXWLBsSJ89TH4j663up6PjBwKa4

###

POST http://localhost:8000/api/refresh
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoicGF1Y2hpaWUiLCJpYXQiOjE2OTE2Nzg0NDMsImV4cCI6MTY5MTY3OTM0MywiYXVkIjoiY2xpZW50IiwiaXNzIjoicGFzeWVudGUiLCJzdWIiOiJ1bmRlZmluZWQifQ.Wykhb11um9zKwLqiN37HgNuoVsOeyy7fWD2HyywFxkA

###

POST http://localhost:8000/api/login
content-type: application/json

{
  "username": "pauchiie",
  "password": "my_password12345"
}

###

POST http://localhost:8000/api/login
content-type: application/json

{
  "username": "pagiy003",
  "password": "admin12345"
}

###

GET http://localhost:8000/api/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiUGF1bGFfQWRtaW4iLCJpYXQiOjE2OTAyNDUyNjMsImV4cCI6MTY5MDMzMTY2MywiYXVkIjoiYWRtaW4iLCJpc3MiOiJwYXN5ZW50ZSIsInN1YiI6IjEifQ.jn-o-W13zIiwcAZzp6B3RE264d7ZT0N3aQvV2YH0GHY

###

GET http://localhost:8000/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiUGF1bGFfQ2xpZW50IiwiaWF0IjoxNjkwMjQ1OTk1LCJleHAiOjE2OTAyNDYyOTUsImF1ZCI6ImNsaWVudCIsImlzcyI6InBhc3llbnRlIiwic3ViIjoiMSJ9._gFPbGUA8aMfu_jxhQ9OZT_YbvyquaT3ZRVBZ1tNfGQ

###

POST http://localhost:8000/api/register
Content-Type: application/json

{
  "username": "pagiy005",
  "password": "admin12345",
  "user_type": "admin"
}